[package]
name = "day4"
version = "0.1.0"
authors = ["warren.biltz <warren.biltz@mx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

[[bin]]
name = "day4"
path = "day4.rs"
