[package]
name = "day5"
version = "0.1.0"
authors = ["warren.biltz <warren.biltz@mx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day5"
path = "day5.rs"
